### ISSUE TITLE
add a simple example of a gevent wsgi server using pistil?

### ISSUE THREAD

**Issue by dropwhile** [meebo/pistil#5]
Maybe something built off one of the [example gevent wsgi servers](https://bitbucket.org/denis/gevent/src/eccc15e6294e/examples/wsgiserver.py)?

**Comment by ksamuel** [comment]
Indeed, that would make the creation of HTTP backend for workers much easier. For now I don't know how to do this, so I'm parsing the HTTP manually.

**Comment by dropwhile** [comment]
old
